// <auto-generated />
using Dosney.Progress.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dosney.Progress.Migrations
{
    [DbContext(typeof(ProgressDbContext))]
    [Migration("20220529105432_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dosney.Progress.Database.ProgressSession", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("text")
                        .HasColumnName("session_id");

                    b.Property<long>("ProgressFrom")
                        .HasColumnType("bigint")
                        .HasColumnName("progress_from");

                    b.Property<long>("ProgressTo")
                        .HasColumnType("bigint")
                        .HasColumnName("progress_to");

                    b.Property<long>("TimestampFrom")
                        .HasColumnType("bigint")
                        .HasColumnName("timestamp_from");

                    b.Property<long>("TimestampTo")
                        .HasColumnType("bigint")
                        .HasColumnName("timestamp_to");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("VideoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("video_id");

                    b.HasKey("SessionId")
                        .HasName("pk_progress_sessions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_progress_sessions_user_id");

                    b.HasIndex("VideoId")
                        .HasDatabaseName("ix_progress_sessions_video_id");

                    b.ToTable("progress_sessions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
